# Generated by Django 5.0.7 on 2024-07-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="full_address",
            field=models.TextField(blank=True),
        ),
    ]
